---
# - import_tasks: test.yml
#   tags: test

# tasks file for hardening
- import_tasks: pre_tasks.yml
  tags: pre_tasks

- import_tasks: 1.6.1.yml
  tags: 1.6.1

- import_tasks: 1.6.2.yml
  tags: 1.6.2

- import_tasks: 2.1.1.yml
  tags: 2.1.1

- import_tasks: 2.1.2.yml
  tags: 2.1.2

- import_tasks: 2.1.3.yml
  tags: 2.1.3
